CREATE TABLE [dbo].[Comentarios]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Comentario] NVARCHAR(1000) NOT NULL, 
    [UserId] UNIQUEIDENTIFIER NOT NULL,
    [CreatedDate] DATETIME2 NULL, 
    [UpdatedDate] DATETIME2 NULL
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
)
