CREATE TABLE [dbo].[RoadmapVotes]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
	[RoadmapId] UNIQUEIDENTIFIER NOT NULL, 
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY ([RoadmapId]) REFERENCES [dbo].[Roadmaps] ([Id]) ON DELETE CASCADE,
	UNIQUE ([RoadmapId], [UserId])

)
